### ISSUE TITLE
Social networks text created

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/state-of-green-software#149]
Parent issue #129 

Come up with a better text for sharing insights on LinkedIn, Twitter

Tab 2 "Social Sharing Text" The [link](https://docs.google.com/spreadsheets/d/1YwwKby8HWJ3J1Xz_M6e3Wobg9BoSCxVMZq_Wji714Tw/edit?usp=sharing) is here

![image](https://github.com/Green-Software-Foundation/state-of-green-software/assets/125550685/2f51dd8c-ae43-495f-becc-8c5ac090569d)

**Comment by NAMRATA-WOKE** [comment]
Done. Made some edits mostly to the URLs. Ended all descriptions with a period.

**Comment by NAMRATA-WOKE** [comment]
@Oleg-Zhymolokhov @osamajandali almost done - 2 more to go! **View tab 2.** 

https://docs.google.com/spreadsheets/d/1YwwKby8HWJ3J1Xz_M6e3Wobg9BoSCxVMZq_Wji714Tw/edit?usp=sharing

**Comment by osamajandali** [comment]
@NAMRATA-WOKE I think you forgot to count the characters in some of the tweets, as there are many tweets that exceeded the limit after sharing it. 
Keep in mind we are sharing a link in the tweet, and that link is shortened to 23 characters, and new lines count as well against 280 character limit.

**Comment by NAMRATA-WOKE** [comment]
@osamajandali now that I know the URL, I'll modify the ones that are over.

**Comment by NAMRATA-WOKE** [comment]
@osamajandali @Oleg-Zhymolokhov updated. https://docs.google.com/spreadsheets/d/1YwwKby8HWJ3J1Xz_M6e3Wobg9BoSCxVMZq_Wji714Tw/edit#gid=2115859291
